runtime: php55
api_version: 1

handlers:
- url: /
  script: login.php
- url: /register
  script: register.php
- url: /main
  script: main.php
- url: /login
  script: login.php
- url: /logout
  script: logout.php
